# Generated by Django 4.2.27 on 2025-12-14 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('pattern_json', models.JSONField(help_text='Full pattern structure from ExtractorPatternAgent')),
                ('success_rate', models.FloatField(default=0.0, help_text='Percentage of successful extractions')),
                ('total_attempts', models.IntegerField(default=0)),
                ('successful_attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_validated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pattern',
                'verbose_name_plural': 'Patterns',
                'ordering': ['domain'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(max_length=500)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('available', models.BooleanField(default=True)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('priority', models.CharField(choices=[('high', 'High - Check every 15 minutes'), ('normal', 'Normal - Check every hour'), ('low', 'Low - Check daily')], default='normal', max_length=10)),
                ('check_interval', models.IntegerField(default=3600, help_text='Check interval in seconds')),
                ('active', models.BooleanField(default=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('last_viewed', models.DateTimeField(blank=True, null=True)),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, help_text='Alert when price drops to or below this value', max_digits=10, null=True)),
                ('notify_on_drop', models.BooleanField(default=True)),
                ('notify_on_restock', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pattern_version', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-last_viewed', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('available', models.BooleanField(default=True)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(default=1.0, help_text='Extraction confidence (0.0-1.0)')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='app.product')),
            ],
            options={
                'verbose_name': 'Price History',
                'verbose_name_plural': 'Price Histories',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('price_drop', 'Price Drop'), ('target_reached', 'Target Price Reached'), ('restock', 'Back in Stock'), ('price_spike', 'Price Increased')], max_length=20)),
                ('message', models.TextField()),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField()),
                ('extraction_method', models.CharField(blank=True, help_text='Method used: css, xpath, jsonld, meta', max_length=50, null=True)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Fetch duration in milliseconds', null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fetch_logs', to='app.product')),
            ],
            options={
                'verbose_name': 'Fetch Log',
                'verbose_name_plural': 'Fetch Logs',
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('pattern_generation_failed', 'Pattern Generation Failed'), ('pattern_low_confidence', 'Pattern Low Confidence'), ('fetch_failing_repeatedly', 'Fetch Failing Repeatedly')], max_length=50)),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('url', models.URLField(max_length=1000)),
                ('error_message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('wont_fix', "Won't Fix")], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Flag',
                'verbose_name_plural': 'Admin Flags',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Time spent on page', null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User View',
                'verbose_name_plural': 'User Views',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['user', '-viewed_at'], name='app_uservie_user_id_bf9524_idx'), models.Index(fields=['product', '-viewed_at'], name='app_uservie_product_65a801_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['user', 'active'], name='app_product_user_id_61d7da_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['domain'], name='app_product_domain_937da8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['last_checked'], name='app_product_last_ch_af8876_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['priority', 'active'], name='app_product_priorit_b707a8_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['product', '-recorded_at'], name='app_pricehi_product_c5433e_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read', '-created_at'], name='app_notific_user_id_caa313_idx'),
        ),
        migrations.AddIndex(
            model_name='fetchlog',
            index=models.Index(fields=['product', '-fetched_at'], name='app_fetchlo_product_c9fa81_idx'),
        ),
        migrations.AddIndex(
            model_name='fetchlog',
            index=models.Index(fields=['success', '-fetched_at'], name='app_fetchlo_success_8ac23f_idx'),
        ),
        migrations.AddIndex(
            model_name='adminflag',
            index=models.Index(fields=['status', '-created_at'], name='app_adminfl_status_01e3dd_idx'),
        ),
        migrations.AddIndex(
            model_name='adminflag',
            index=models.Index(fields=['domain', 'status'], name='app_adminfl_domain_2bbef2_idx'),
        ),
    ]
