# Generated by Django 4.2.27 on 2025-12-28 17:11

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tier', models.CharField(choices=[('free', 'Registrert bruker'), ('supporter', 'Støttebruker'), ('ultimate', 'Ultimate')], db_index=True, default='free', help_text='User subscription tier', max_length=20)),
                ('tier_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdminFlag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('flag_type', models.CharField(choices=[('pattern_generation_failed', 'Pattern Generation Failed'), ('pattern_low_confidence', 'Pattern Low Confidence'), ('fetch_failing_repeatedly', 'Fetch Failing Repeatedly'), ('store_rate_limited', 'Store Rate Limited'), ('duplicate_products', 'Potential Duplicate Products')], max_length=50)),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('url', models.URLField(max_length=1000)),
                ('error_message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('wont_fix', "Won't Fix")], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Admin Flag',
                'verbose_name_plural': 'Admin Flags',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractorVersion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('commit_hash', models.CharField(db_index=True, help_text='Git commit SHA hash (40 characters)', max_length=40, unique=True)),
                ('extractor_module', models.CharField(db_index=True, help_text='Python extractor module name (e.g., "generated_extractors.komplett_no")', max_length=255)),
                ('commit_message', models.TextField(blank=True, help_text='Git commit message')),
                ('commit_author', models.CharField(blank=True, help_text='Git commit author', max_length=200)),
                ('commit_date', models.DateTimeField(blank=True, help_text='Git commit timestamp', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional git metadata (branch, tags, etc.)')),
                ('domain', models.CharField(blank=True, db_index=True, help_text='Domain this extractor handles (e.g., komplett.no)', max_length=255, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Whether this version is currently deployed for this domain')),
                ('success_rate', models.FloatField(default=0.0, help_text='Percentage of successful extractions for this version (0.0-1.0)')),
                ('total_attempts', models.IntegerField(default=0, help_text='Total extraction attempts with this version')),
                ('successful_attempts', models.IntegerField(default=0, help_text='Number of successful extraction attempts')),
                ('last_validated', models.DateTimeField(blank=True, help_text='Last time this version was validated', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this version was registered in the system')),
            ],
            options={
                'verbose_name': 'Extractor Version',
                'verbose_name_plural': 'Extractor Versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('price_drop', 'Price Drop'), ('target_reached', 'Target Price Reached'), ('restock', 'Back in Stock'), ('price_spike', 'Price Increased'), ('new_listing', 'New Store Listing')], max_length=20)),
                ('message', models.TextField()),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('service', models.CharField(choices=[('celery', 'Celery Task'), ('fetcher', 'Price Fetcher'), ('extractor', 'Pattern Extractor')], db_index=True, max_length=50)),
                ('task_id', models.CharField(blank=True, db_index=True, help_text='Celery task ID for correlation', max_length=100, null=True)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, max_length=10)),
                ('event', models.CharField(db_index=True, help_text='Structured event name (e.g., fetch_page_started, pattern_found)', max_length=100)),
                ('message', models.TextField(blank=True, help_text='Human-readable message')),
                ('context', models.JSONField(blank=True, default=dict, help_text='Structured context data (all log fields as JSON)')),
                ('filename', models.CharField(blank=True, help_text='Source file (e.g., fetcher.py, storage.py)', max_length=100)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Operation duration in milliseconds', null=True)),
            ],
            options={
                'verbose_name': 'Operation Log',
                'verbose_name_plural': 'Operation Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('available', models.BooleanField(default=True)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(default=1.0, help_text='Extraction confidence (0.0-1.0)')),
                ('extraction_method', models.CharField(blank=True, help_text='Method used: css, xpath, jsonld, meta', max_length=50, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Price History',
                'verbose_name_plural': 'Price Histories',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=500)),
                ('canonical_name', models.CharField(db_index=True, help_text='Normalized name for matching (lowercase, no special chars)', max_length=500)),
                ('brand', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('model_number', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('ean', models.CharField(blank=True, db_index=True, max_length=13, null=True, unique=True)),
                ('upc', models.CharField(blank=True, db_index=True, max_length=12, null=True, unique=True)),
                ('isbn', models.CharField(blank=True, db_index=True, max_length=13, null=True, unique=True)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscriber_count', models.IntegerField(default=0, help_text='Number of users subscribed')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.IntegerField(choices=[(2, 'Normal - Check every hour'), (1, 'Low - Check daily')], db_index=True, default=2, help_text='User priority affects product check frequency')),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, help_text='Alert when ANY store reaches this price', max_digits=10, null=True)),
                ('notify_on_drop', models.BooleanField(default=True)),
                ('notify_on_restock', models.BooleanField(default=False)),
                ('notify_on_target', models.BooleanField(default=True, help_text='Notify when target price is reached')),
                ('view_count', models.IntegerField(default=0)),
                ('last_viewed', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
                'ordering': ['-last_viewed', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserView',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Time spent on page', null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='app.usersubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User View',
                'verbose_name_plural': 'User Views',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(help_text='User feedback message')),
                ('page_url', models.CharField(help_text='URL path where feedback was submitted', max_length=500)),
                ('page_title', models.CharField(blank=True, help_text='Page title for context', max_length=200)),
                ('view_name', models.CharField(blank=True, help_text='Django view name if available', max_length=100)),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Additional context: browser, screen size, etc.')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('implemented', 'Implemented'), ('dismissed', 'Dismissed')], db_index=True, default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from admin review')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_feedback', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Feedback',
                'verbose_name_plural': 'User Feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('country', models.CharField(blank=True, help_text='ISO country code', max_length=2)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('logo_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('active', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False, help_text='Store verified and trusted for scraping')),
                ('rate_limit_seconds', models.IntegerField(default=2, help_text='Minimum seconds between requests to this store')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['domain'], name='app_store_domain_a0c279_idx'), models.Index(fields=['active', 'verified'], name='app_store_active_d4091d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductRelation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('weight', models.SmallIntegerField(choices=[(-1, 'Not the same'), (0, 'Dismissed'), (1, 'Same product')], db_index=True, help_text='User vote: -1 (different), 0 (dismissed), 1 (same)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('product_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_first', to='app.product')),
                ('product_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_second', to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_relations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Relation',
                'verbose_name_plural': 'Product Relations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(db_index=True, max_length=1000, unique=True)),
                ('store_product_id', models.CharField(blank=True, help_text='Store-specific product ID (e.g., ASIN for Amazon)', max_length=200)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('available', models.BooleanField(default=True)),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('seller_name', models.CharField(blank=True, max_length=200)),
                ('seller_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('active', models.BooleanField(default=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('last_available', models.DateTimeField(blank=True, help_text='Last time product was in stock', null=True)),
                ('pattern_version', models.CharField(blank=True, help_text='Deprecated: use extractor_version FK instead', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extractor_version', models.ForeignKey(blank=True, help_text='Git version used to extract this listing data', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='app.extractorversion')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='app.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='app.store')),
            ],
            options={
                'verbose_name': 'Product Listing',
                'verbose_name_plural': 'Product Listings',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['canonical_name'], name='app_product_canonic_abbb15_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'model_number'], name='app_product_brand_9ddb0b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['ean'], name='app_product_ean_268ec7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['upc'], name='app_product_upc_919e91_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['subscriber_count'], name='app_product_subscri_7880a4_idx'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='app.productlisting'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to='app.productlisting'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to='app.product'),
        ),
        migrations.AddField(
            model_name='notification',
            name='listing',
            field=models.ForeignKey(help_text='Specific store listing for this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app.productlisting'),
        ),
        migrations.AddField(
            model_name='notification',
            name='subscription',
            field=models.ForeignKey(help_text='User subscription that triggered this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app.usersubscription'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extractorversion',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Store this extractor is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extractor_versions', to='app.store'),
        ),
        migrations.AddField(
            model_name='adminflag',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_flags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminflag',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags', to='app.store'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tier_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tier_updates_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='userview',
            index=models.Index(fields=['user', '-viewed_at'], name='app_uservie_user_id_bf9524_idx'),
        ),
        migrations.AddIndex(
            model_name='userview',
            index=models.Index(fields=['subscription', '-viewed_at'], name='app_uservie_subscri_a99c7f_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user', 'active'], name='app_usersub_user_id_a1a8eb_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['product', 'active'], name='app_usersub_product_3fabef_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['priority', 'active'], name='app_usersub_priorit_f27254_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user', 'active', '-last_viewed'], name='app_usersub_user_id_0b7968_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usersubscription',
            unique_together={('user', 'product')},
        ),
        migrations.AddIndex(
            model_name='userfeedback',
            index=models.Index(fields=['user', '-created_at'], name='app_userfee_user_id_3910b6_idx'),
        ),
        migrations.AddIndex(
            model_name='userfeedback',
            index=models.Index(fields=['status', '-created_at'], name='app_userfee_status_074107_idx'),
        ),
        migrations.AddIndex(
            model_name='userfeedback',
            index=models.Index(fields=['-created_at'], name='app_userfee_created_9e6789_idx'),
        ),
        migrations.AddIndex(
            model_name='productrelation',
            index=models.Index(fields=['user', '-updated_at'], name='app_product_user_id_7aa877_idx'),
        ),
        migrations.AddIndex(
            model_name='productrelation',
            index=models.Index(fields=['product_1', 'product_2'], name='app_product_product_aec1d4_idx'),
        ),
        migrations.AddIndex(
            model_name='productrelation',
            index=models.Index(fields=['product_2', 'product_1'], name='app_product_product_37aec9_idx'),
        ),
        migrations.AddIndex(
            model_name='productrelation',
            index=models.Index(fields=['weight', '-updated_at'], name='app_product_weight_658fc9_idx'),
        ),
        migrations.AddConstraint(
            model_name='productrelation',
            constraint=models.UniqueConstraint(fields=('user', 'product_1', 'product_2'), name='unique_user_product_relation'),
        ),
        migrations.AddConstraint(
            model_name='productrelation',
            constraint=models.CheckConstraint(check=models.Q(('product_1_id__lt', models.F('product_2_id'))), name='product_1_less_than_product_2', violation_error_message='product_1 must be less than product_2'),
        ),
        migrations.AddIndex(
            model_name='productlisting',
            index=models.Index(fields=['product', 'store'], name='app_product_product_82f656_idx'),
        ),
        migrations.AddIndex(
            model_name='productlisting',
            index=models.Index(fields=['store', 'active'], name='app_product_store_i_dc1545_idx'),
        ),
        migrations.AddIndex(
            model_name='productlisting',
            index=models.Index(fields=['url'], name='app_product_url_262b7c_idx'),
        ),
        migrations.AddIndex(
            model_name='productlisting',
            index=models.Index(fields=['last_checked'], name='app_product_last_ch_d2bf55_idx'),
        ),
        migrations.AddIndex(
            model_name='productlisting',
            index=models.Index(fields=['current_price'], name='app_product_current_9c9ecf_idx'),
        ),
        migrations.AddIndex(
            model_name='productlisting',
            index=models.Index(fields=['available'], name='app_product_availab_e04630_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productlisting',
            unique_together={('product', 'store', 'url')},
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['listing', '-recorded_at'], name='app_pricehi_listing_8aff97_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['listing', 'available', '-recorded_at'], name='app_pricehi_listing_49955f_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['-recorded_at'], name='app_pricehi_recorde_ebf952_idx'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['service', '-timestamp'], name='app_operati_service_409214_idx'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['task_id', '-timestamp'], name='app_operati_task_id_fd748c_idx'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['level', '-timestamp'], name='app_operati_level_35d7a3_idx'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['listing', '-timestamp'], name='app_operati_listing_f800ee_idx'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['product', '-timestamp'], name='app_operati_product_d82a4c_idx'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['event', '-timestamp'], name='app_operati_event_69d104_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read', '-created_at'], name='app_notific_user_id_caa313_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['subscription', '-created_at'], name='app_notific_subscri_1f5a44_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['listing', '-created_at'], name='app_notific_listing_4462d2_idx'),
        ),
        migrations.AddIndex(
            model_name='extractorversion',
            index=models.Index(fields=['commit_hash'], name='app_extract_commit__21e1f8_idx'),
        ),
        migrations.AddIndex(
            model_name='extractorversion',
            index=models.Index(fields=['extractor_module', '-created_at'], name='app_extract_extract_004956_idx'),
        ),
        migrations.AddIndex(
            model_name='extractorversion',
            index=models.Index(fields=['-created_at'], name='app_extract_created_7c9bd9_idx'),
        ),
        migrations.AddIndex(
            model_name='extractorversion',
            index=models.Index(fields=['domain', 'is_active'], name='app_extract_domain_9a2710_idx'),
        ),
        migrations.AddConstraint(
            model_name='extractorversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('domain', 'is_active'), name='unique_active_version_per_domain'),
        ),
        migrations.AddIndex(
            model_name='adminflag',
            index=models.Index(fields=['status', '-created_at'], name='app_adminfl_status_01e3dd_idx'),
        ),
        migrations.AddIndex(
            model_name='adminflag',
            index=models.Index(fields=['domain', 'status'], name='app_adminfl_domain_2bbef2_idx'),
        ),
        migrations.AddIndex(
            model_name='adminflag',
            index=models.Index(fields=['store', 'status'], name='app_adminfl_store_i_0a24df_idx'),
        ),
    ]
