# Generated by Django 4.2.27 on 2025-12-14 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminFlag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('flag_type', models.CharField(choices=[('pattern_generation_failed', 'Pattern Generation Failed'), ('pattern_low_confidence', 'Pattern Low Confidence'), ('fetch_failing_repeatedly', 'Fetch Failing Repeatedly'), ('store_rate_limited', 'Store Rate Limited'), ('duplicate_products', 'Potential Duplicate Products')], max_length=50)),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('url', models.URLField(max_length=1000)),
                ('error_message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('wont_fix', "Won't Fix")], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Admin Flag',
                'verbose_name_plural': 'Admin Flags',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FetchLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('success', models.BooleanField()),
                ('extraction_method', models.CharField(blank=True, help_text='Method used: css, xpath, jsonld, meta', max_length=50, null=True)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Fetch duration in milliseconds', null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fetch Log',
                'verbose_name_plural': 'Fetch Logs',
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('price_drop', 'Price Drop'), ('target_reached', 'Target Price Reached'), ('restock', 'Back in Stock'), ('price_spike', 'Price Increased'), ('new_listing', 'New Store Listing')], max_length=20)),
                ('message', models.TextField()),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('pattern_json', models.JSONField(help_text='Full pattern structure from ExtractorPatternAgent')),
                ('success_rate', models.FloatField(default=0.0, help_text='Percentage of successful extractions')),
                ('total_attempts', models.IntegerField(default=0)),
                ('successful_attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_validated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pattern',
                'verbose_name_plural': 'Patterns',
                'ordering': ['domain'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('available', models.BooleanField(default=True)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(default=1.0, help_text='Extraction confidence (0.0-1.0)')),
                ('extraction_method', models.CharField(blank=True, help_text='Method used: css, xpath, jsonld, meta', max_length=50, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Price History',
                'verbose_name_plural': 'Price Histories',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=500)),
                ('canonical_name', models.CharField(db_index=True, help_text='Normalized name for matching (lowercase, no special chars)', max_length=500)),
                ('brand', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('model_number', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('ean', models.CharField(blank=True, db_index=True, max_length=13, null=True, unique=True)),
                ('upc', models.CharField(blank=True, db_index=True, max_length=12, null=True, unique=True)),
                ('isbn', models.CharField(blank=True, db_index=True, max_length=13, null=True, unique=True)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscriber_count', models.IntegerField(default=0, help_text='Number of users subscribed')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.IntegerField(choices=[(3, 'High - Check every 15 minutes'), (2, 'Normal - Check every hour'), (1, 'Low - Check daily')], db_index=True, default=2, help_text='User priority affects product check frequency')),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, help_text='Alert when ANY store reaches this price', max_digits=10, null=True)),
                ('notify_on_drop', models.BooleanField(default=True)),
                ('notify_on_restock', models.BooleanField(default=False)),
                ('notify_on_target', models.BooleanField(default=True, help_text='Notify when target price is reached')),
                ('view_count', models.IntegerField(default=0)),
                ('last_viewed', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
                'ordering': ['-last_viewed', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserView',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Time spent on page', null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='app.usersubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User View',
                'verbose_name_plural': 'User Views',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('country', models.CharField(blank=True, help_text='ISO country code', max_length=2)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('logo_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('active', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False, help_text='Store verified and trusted for scraping')),
                ('rate_limit_seconds', models.IntegerField(default=2, help_text='Minimum seconds between requests to this store')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['domain'], name='app_store_domain_a0c279_idx'), models.Index(fields=['active', 'verified'], name='app_store_active_d4091d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(db_index=True, max_length=1000, unique=True)),
                ('store_product_id', models.CharField(blank=True, help_text='Store-specific product ID (e.g., ASIN for Amazon)', max_length=200)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('available', models.BooleanField(default=True)),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('seller_name', models.CharField(blank=True, max_length=200)),
                ('seller_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('active', models.BooleanField(default=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('last_available', models.DateTimeField(blank=True, help_text='Last time product was in stock', null=True)),
                ('pattern_version', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='app.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='app.store')),
            ],
            options={
                'verbose_name': 'Product Listing',
                'verbose_name_plural': 'Product Listings',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['canonical_name'], name='app_product_canonic_abbb15_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'model_number'], name='app_product_brand_9ddb0b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['ean'], name='app_product_ean_268ec7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['upc'], name='app_product_upc_919e91_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['subscriber_count'], name='app_product_subscri_7880a4_idx'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='app.productlisting'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='store',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pattern', to='app.store'),
        ),
        migrations.AddField(
            model_name='notification',
            name='listing',
            field=models.ForeignKey(help_text='Specific store listing for this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app.productlisting'),
        ),
        migrations.AddField(
            model_name='notification',
            name='subscription',
            field=models.ForeignKey(help_text='User subscription that triggered this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app.usersubscription'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fetchlog',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fetch_logs', to='app.productlisting'),
        ),
        migrations.AddField(
            model_name='adminflag',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_flags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminflag',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags', to='app.store'),
        ),
        migrations.AddIndex(
            model_name='userview',
            index=models.Index(fields=['user', '-viewed_at'], name='app_uservie_user_id_bf9524_idx'),
        ),
        migrations.AddIndex(
            model_name='userview',
            index=models.Index(fields=['subscription', '-viewed_at'], name='app_uservie_subscri_a99c7f_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user', 'active'], name='app_usersub_user_id_a1a8eb_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['product', 'active'], name='app_usersub_product_3fabef_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['priority', 'active'], name='app_usersub_priorit_f27254_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user', 'active', '-last_viewed'], name='app_usersub_user_id_0b7968_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usersubscription',
            unique_together={('user', 'product')},
        ),
        migrations.AddIndex(
            model_name='productlisting',
            index=models.Index(fields=['product', 'store'], name='app_product_product_82f656_idx'),
        ),
        migrations.AddIndex(
            model_name='productlisting',
            index=models.Index(fields=['store', 'active'], name='app_product_store_i_dc1545_idx'),
        ),
        migrations.AddIndex(
            model_name='productlisting',
            index=models.Index(fields=['url'], name='app_product_url_262b7c_idx'),
        ),
        migrations.AddIndex(
            model_name='productlisting',
            index=models.Index(fields=['last_checked'], name='app_product_last_ch_d2bf55_idx'),
        ),
        migrations.AddIndex(
            model_name='productlisting',
            index=models.Index(fields=['current_price'], name='app_product_current_9c9ecf_idx'),
        ),
        migrations.AddIndex(
            model_name='productlisting',
            index=models.Index(fields=['available'], name='app_product_availab_e04630_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productlisting',
            unique_together={('product', 'store', 'url')},
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['listing', '-recorded_at'], name='app_pricehi_listing_8aff97_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['listing', 'available', '-recorded_at'], name='app_pricehi_listing_49955f_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['-recorded_at'], name='app_pricehi_recorde_ebf952_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read', '-created_at'], name='app_notific_user_id_caa313_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['subscription', '-created_at'], name='app_notific_subscri_1f5a44_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['listing', '-created_at'], name='app_notific_listing_4462d2_idx'),
        ),
        migrations.AddIndex(
            model_name='fetchlog',
            index=models.Index(fields=['listing', '-fetched_at'], name='app_fetchlo_listing_5e6d37_idx'),
        ),
        migrations.AddIndex(
            model_name='fetchlog',
            index=models.Index(fields=['success', '-fetched_at'], name='app_fetchlo_success_8ac23f_idx'),
        ),
        migrations.AddIndex(
            model_name='adminflag',
            index=models.Index(fields=['status', '-created_at'], name='app_adminfl_status_01e3dd_idx'),
        ),
        migrations.AddIndex(
            model_name='adminflag',
            index=models.Index(fields=['domain', 'status'], name='app_adminfl_domain_2bbef2_idx'),
        ),
        migrations.AddIndex(
            model_name='adminflag',
            index=models.Index(fields=['store', 'status'], name='app_adminfl_store_i_0a24df_idx'),
        ),
    ]
