# Generated by Django 4.2.27 on 2025-12-14 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='priority',
            field=models.IntegerField(choices=[(2, 'Normal - Check every hour'), (1, 'Low - Check daily')], db_index=True, default=2, help_text='User priority affects product check frequency'),
        ),
        migrations.CreateModel(
            name='PatternHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('domain', models.CharField(db_index=True, help_text='Denormalized domain for faster queries', max_length=255)),
                ('version_number', models.IntegerField(help_text='Sequential version number per pattern')),
                ('pattern_json', models.JSONField(help_text='Snapshot of pattern at this version')),
                ('change_reason', models.CharField(blank=True, default='', help_text='Reason for this change', max_length=500)),
                ('change_type', models.CharField(choices=[('manual_edit', 'Manual Edit'), ('auto_generated', 'Auto-Generated'), ('api_update', 'API Update'), ('rollback', 'Rollback'), ('auto_save', 'Auto-Save')], default='manual_edit', max_length=50)),
                ('success_rate_at_time', models.FloatField(blank=True, help_text='Success rate when this version was created', null=True)),
                ('total_attempts_at_time', models.IntegerField(default=0, help_text='Total attempts when this version was created')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who made this change', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='app.pattern')),
            ],
            options={
                'verbose_name': 'Pattern History',
                'verbose_name_plural': 'Pattern History',
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['domain', '-created_at'], name='app_pattern_domain_9e2161_idx'), models.Index(fields=['pattern', '-version_number'], name='app_pattern_pattern_cab9a9_idx'), models.Index(fields=['-created_at'], name='app_pattern_created_dde3b6_idx')],
                'unique_together': {('pattern', 'version_number')},
            },
        ),
    ]
