# Generated by Django 4.2.27 on 2025-12-28 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referral_tier_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When referral-earned tier expires (null for non-referral tiers)', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referral_tier_granted_count',
            field=models.IntegerField(default=0, help_text='Number of times user has earned referral tier'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referral_tier_source',
            field=models.CharField(choices=[('none', 'No Active Tier Source'), ('referral', 'Referral Earned'), ('payment', 'Paid Subscription')], db_index=True, default='none', help_text='How current tier was obtained', max_length=20),
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='Short unique referral code (e.g., ABCD1234EFGH)', max_length=12, unique=True)),
                ('total_visits', models.IntegerField(default=0, help_text='Total number of visits to referral link')),
                ('unique_visits', models.IntegerField(default=0, help_text='Number of unique visits (deduplicated)')),
                ('conversions', models.IntegerField(default=0, help_text='Number of users who registered via this referral')),
                ('last_reward_granted_at', models.DateTimeField(blank=True, help_text='When last 30-day reward was granted', null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_code', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral Code',
                'verbose_name_plural': 'Referral Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTierHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('old_tier', models.CharField(max_length=20)),
                ('new_tier', models.CharField(max_length=20)),
                ('source', models.CharField(choices=[('default', 'Default (Free)'), ('payment', 'Payment'), ('referral', 'Referral Reward'), ('admin', 'Admin Manual Change'), ('promotion', 'Promotional Grant'), ('expiration', 'Tier Expired')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tier_changes_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Tier History',
                'verbose_name_plural': 'User Tier Histories',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['user', '-changed_at'], name='app_usertie_user_id_ed648c_idx'), models.Index(fields=['source', '-changed_at'], name='app_usertie_source_2ab7bf_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReferralVisit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('visitor_cookie_id', models.UUIDField(blank=True, db_index=True, help_text='Tracking cookie ID (1-year persistent)', null=True)),
                ('visitor_ip_hash', models.CharField(blank=True, db_index=True, help_text='Hashed IP address (SHA256) for privacy', max_length=64, null=True)),
                ('visitor_fingerprint', models.CharField(blank=True, help_text='Optional browser fingerprint for future use', max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('referer', models.CharField(blank=True, max_length=500)),
                ('landing_page', models.CharField(blank=True, help_text='Page they landed on after clicking referral', max_length=500)),
                ('session_key', models.CharField(blank=True, help_text='Django session key if available', max_length=40)),
                ('is_unique', models.BooleanField(db_index=True, default=False, help_text='Counted as unique visit toward referral rewards')),
                ('duplicate_reason', models.CharField(blank=True, help_text='Why marked as duplicate (if not unique)', max_length=100)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('visited_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('converted_user', models.ForeignKey(blank=True, help_text='User who registered from this visit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversion_from_referral', to=settings.AUTH_USER_MODEL)),
                ('referral_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='app.referralcode')),
                ('visitor_user', models.ForeignKey(blank=True, help_text='If visitor was logged in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral Visit',
                'verbose_name_plural': 'Referral Visits',
                'ordering': ['-visited_at'],
                'indexes': [models.Index(fields=['referral_code', '-visited_at'], name='app_referra_referra_4f508e_idx'), models.Index(fields=['referral_code', 'is_unique'], name='app_referra_referra_801d96_idx'), models.Index(fields=['visitor_cookie_id', 'referral_code'], name='app_referra_visitor_21d9d1_idx'), models.Index(fields=['visitor_ip_hash', 'referral_code'], name='app_referra_visitor_fd40bc_idx'), models.Index(fields=['visitor_user', 'referral_code'], name='app_referra_visitor_32218b_idx'), models.Index(fields=['-visited_at'], name='app_referra_visited_5d2203_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='referralcode',
            index=models.Index(fields=['code'], name='app_referra_code_3ce711_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcode',
            index=models.Index(fields=['user', 'active'], name='app_referra_user_id_aca09f_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcode',
            index=models.Index(fields=['-unique_visits'], name='app_referra_unique__e11243_idx'),
        ),
    ]
