# Generated by Django 4.2.27 on 2025-12-15 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_usersubscription_priority_patternhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('service', models.CharField(choices=[('celery', 'Celery Task'), ('fetcher', 'Price Fetcher'), ('extractor', 'Pattern Extractor')], db_index=True, max_length=50)),
                ('task_id', models.CharField(blank=True, db_index=True, help_text='Celery task ID for correlation', max_length=100, null=True)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, max_length=10)),
                ('event', models.CharField(db_index=True, help_text='Structured event name (e.g., fetch_page_started, pattern_found)', max_length=100)),
                ('message', models.TextField(blank=True, help_text='Human-readable message')),
                ('context', models.JSONField(blank=True, default=dict, help_text='Structured context data (all log fields as JSON)')),
                ('filename', models.CharField(blank=True, help_text='Source file (e.g., fetcher.py, storage.py)', max_length=100)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Operation duration in milliseconds', null=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to='app.productlisting')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to='app.product')),
            ],
            options={
                'verbose_name': 'Operation Log',
                'verbose_name_plural': 'Operation Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['service', '-timestamp'], name='app_operati_service_409214_idx'), models.Index(fields=['task_id', '-timestamp'], name='app_operati_task_id_fd748c_idx'), models.Index(fields=['level', '-timestamp'], name='app_operati_level_35d7a3_idx'), models.Index(fields=['listing', '-timestamp'], name='app_operati_listing_f800ee_idx'), models.Index(fields=['product', '-timestamp'], name='app_operati_product_d82a4c_idx'), models.Index(fields=['event', '-timestamp'], name='app_operati_event_69d104_idx')],
            },
        ),
    ]
