# Generated by Django 4.2.27 on 2025-12-30 14:21

from django.db import migrations, models
from urllib.parse import urlparse, urlunparse


def backfill_url_base(apps, schema_editor):
    """
    Backfill url_base field for existing ProductListing records.
    Normalizes URLs by removing query parameters and fragments.
    """
    ProductListing = apps.get_model('app', 'ProductListing')

    def get_url_base_for_comparison(url):
        """Get normalized URL base without query params or fragments."""
        try:
            parsed = urlparse(url)
            normalized = parsed._replace(query='', fragment='')
            return urlunparse(normalized)
        except Exception:
            # If parsing fails, return original URL
            return url

    # Backfill in batches for better performance
    batch_size = 500
    total_updated = 0

    listings = ProductListing.objects.all()
    total_count = listings.count()

    for listing in listings.iterator(chunk_size=batch_size):
        listing.url_base = get_url_base_for_comparison(listing.url)
        listing.save(update_fields=['url_base'])
        total_updated += 1

        if total_updated % batch_size == 0:
            print(f"Backfilled {total_updated}/{total_count} listings...")

    print(f"Backfill complete: {total_updated} listings updated")


def reverse_backfill(apps, schema_editor):
    """Reverse migration - clear url_base field."""
    ProductListing = apps.get_model('app', 'ProductListing')
    ProductListing.objects.all().update(url_base='')


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_add_referral_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='url_base',
            field=models.CharField(db_index=True, default='', help_text='Normalized URL without query params or fragments for duplicate detection', max_length=1000),
        ),
        migrations.RunPython(backfill_url_base, reverse_backfill),
        migrations.AlterField(
            model_name='customuser',
            name='referral_tier_source',
            field=models.CharField(choices=[('none', 'No Active Tier Source'), ('referral', 'Referral Earned'), ('payment', 'Paid Subscription'), ('admin', 'Manually Assigned')], db_index=True, default='none', help_text='How current tier was obtained', max_length=20),
        ),
    ]
