# Generated by Django 4.2.27 on 2025-12-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_operationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='extractor_module',
            field=models.CharField(blank=True, db_index=True, help_text='Python extractor module name (e.g., "generated_extractors.komplett_no")', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='pattern_json',
            field=models.JSONField(blank=True, help_text='Full pattern structure from ExtractorPatternAgent (deprecated, use extractor_module)', null=True),
        ),
    ]
