# Generated by Django 4.2.27 on 2025-12-23 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pattern_extractor_module_alter_pattern_pattern_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlisting',
            name='pattern_version',
            field=models.CharField(blank=True, help_text='Deprecated: use extractor_version FK instead', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ExtractorVersion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('commit_hash', models.CharField(db_index=True, help_text='Git commit SHA hash (40 characters)', max_length=40, unique=True)),
                ('extractor_module', models.CharField(db_index=True, help_text='Python extractor module name (e.g., "generated_extractors.komplett_no")', max_length=255)),
                ('commit_message', models.TextField(blank=True, help_text='Git commit message')),
                ('commit_author', models.CharField(blank=True, help_text='Git commit author', max_length=200)),
                ('commit_date', models.DateTimeField(blank=True, help_text='Git commit timestamp', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional git metadata (branch, tags, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this version was registered in the system')),
            ],
            options={
                'verbose_name': 'Extractor Version',
                'verbose_name_plural': 'Extractor Versions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['commit_hash'], name='app_extract_commit__21e1f8_idx'), models.Index(fields=['extractor_module', '-created_at'], name='app_extract_extract_004956_idx'), models.Index(fields=['-created_at'], name='app_extract_created_7c9bd9_idx')],
            },
        ),
        migrations.AddField(
            model_name='pattern',
            name='extractor_version',
            field=models.ForeignKey(blank=True, help_text='Git version of the extractor module', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patterns', to='app.extractorversion'),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='extractor_version',
            field=models.ForeignKey(blank=True, help_text='Git version used to extract this listing data', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='app.extractorversion'),
        ),
    ]
