# Generated by Django 4.2.27 on 2025-12-23 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_productlisting_pattern_version_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FetchLog',
        ),
    ]
