# Generated by Django 4.2.27 on 2025-12-24 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_fetchlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pattern',
            name='pattern_json',
        ),
        migrations.DeleteModel(
            name='PatternHistory',
        ),
    ]
