# Generated by Django 4.2.27 on 2025-12-25 21:29

from django.db import migrations, models
import django.db.models.deletion


def migrate_pattern_to_extractorversion(apps, schema_editor):
    """
    Migrate data from Pattern model to ExtractorVersion.
    For each Pattern, copy its data to the linked ExtractorVersion and mark it as active.
    """
    Pattern = apps.get_model('app', 'Pattern')
    ExtractorVersion = apps.get_model('app', 'ExtractorVersion')

    patterns = Pattern.objects.select_related('extractor_version', 'store').all()

    for pattern in patterns:
        if pattern.extractor_version:
            # Update the linked version with pattern data
            version = pattern.extractor_version
            version.domain = pattern.domain
            version.store = pattern.store
            version.is_active = True
            version.success_rate = pattern.success_rate
            version.total_attempts = pattern.total_attempts
            version.successful_attempts = pattern.successful_attempts
            version.last_validated = pattern.last_validated
            version.save()
        elif pattern.extractor_module:
            # Pattern has no linked version but has a module - create inactive version as historical record
            # This shouldn't normally happen, but handle it gracefully
            print(f"Warning: Pattern {pattern.domain} has no extractor_version, creating placeholder")


def reverse_migration(apps, schema_editor):
    """
    Reverse operation: clear ExtractorVersion data that came from Pattern.
    """
    ExtractorVersion = apps.get_model('app', 'ExtractorVersion')

    # Reset all the new fields to defaults
    ExtractorVersion.objects.all().update(
        domain=None,
        store=None,
        is_active=False,
        success_rate=0.0,
        total_attempts=0,
        successful_attempts=0,
        last_validated=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_pattern_json_and_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractorversion',
            name='domain',
            field=models.CharField(blank=True, db_index=True, help_text='Domain this extractor handles (e.g., komplett.no)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='extractorversion',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this version is currently deployed for this domain'),
        ),
        migrations.AddField(
            model_name='extractorversion',
            name='last_validated',
            field=models.DateTimeField(blank=True, help_text='Last time this version was validated', null=True),
        ),
        migrations.AddField(
            model_name='extractorversion',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Store this extractor is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extractor_versions', to='app.store'),
        ),
        migrations.AddField(
            model_name='extractorversion',
            name='success_rate',
            field=models.FloatField(default=0.0, help_text='Percentage of successful extractions for this version (0.0-1.0)'),
        ),
        migrations.AddField(
            model_name='extractorversion',
            name='successful_attempts',
            field=models.IntegerField(default=0, help_text='Number of successful extraction attempts'),
        ),
        migrations.AddField(
            model_name='extractorversion',
            name='total_attempts',
            field=models.IntegerField(default=0, help_text='Total extraction attempts with this version'),
        ),
        # Data migration: copy Pattern data to ExtractorVersion
        migrations.RunPython(
            migrate_pattern_to_extractorversion,
            reverse_code=reverse_migration,
        ),
        migrations.AddIndex(
            model_name='extractorversion',
            index=models.Index(fields=['domain', 'is_active'], name='app_extract_domain_9a2710_idx'),
        ),
        migrations.AddConstraint(
            model_name='extractorversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('domain', 'is_active'), name='unique_active_version_per_domain'),
        ),
        # Remove Pattern model after migration is complete
        migrations.RemoveField(
            model_name='pattern',
            name='extractor_version',
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='store',
        ),
        migrations.DeleteModel(
            name='Pattern',
        ),
    ]
