# Generated by Django 4.2.27 on 2025-12-26 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_extractorversion_domain_extractorversion_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(help_text='User feedback message')),
                ('page_url', models.CharField(help_text='URL path where feedback was submitted', max_length=500)),
                ('page_title', models.CharField(blank=True, help_text='Page title for context', max_length=200)),
                ('view_name', models.CharField(blank=True, help_text='Django view name if available', max_length=100)),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Additional context: browser, screen size, etc.')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('implemented', 'Implemented'), ('dismissed', 'Dismissed')], db_index=True, default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from admin review')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_feedback', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Feedback',
                'verbose_name_plural': 'User Feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='app_userfee_user_id_3910b6_idx'), models.Index(fields=['status', '-created_at'], name='app_userfee_status_074107_idx'), models.Index(fields=['-created_at'], name='app_userfee_created_9e6789_idx')],
            },
        ),
    ]
