# Generated by Django 4.2.27 on 2025-12-27 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_userfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRelation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('weight', models.SmallIntegerField(choices=[(-1, 'Not the same'), (0, 'Dismissed'), (1, 'Same product')], db_index=True, help_text='User vote: -1 (different), 0 (dismissed), 1 (same)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('product_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_first', to='app.product')),
                ('product_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_second', to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_relations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Relation',
                'verbose_name_plural': 'Product Relations',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', '-updated_at'], name='app_product_user_id_7aa877_idx'), models.Index(fields=['product_1', 'product_2'], name='app_product_product_aec1d4_idx'), models.Index(fields=['product_2', 'product_1'], name='app_product_product_37aec9_idx'), models.Index(fields=['weight', '-updated_at'], name='app_product_weight_658fc9_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='productrelation',
            constraint=models.UniqueConstraint(fields=('user', 'product_1', 'product_2'), name='unique_user_product_relation'),
        ),
        migrations.AddConstraint(
            model_name='productrelation',
            constraint=models.CheckConstraint(check=models.Q(('product_1_id__lt', models.F('product_2_id'))), name='product_1_less_than_product_2', violation_error_message='product_1 must be less than product_2'),
        ),
    ]
